# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "BrandBook.Web/Areas/App/ClientApp"
    schedule:
      interval: "daily"

    reviewers:
      - "philipp-c-moser"

    target-branch: "develop"
