//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrandBook.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrandBook.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string auth_back_button_title {
            get {
                return ResourceManager.GetString("auth_back_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string auth_login_input_password {
            get {
                return ResourceManager.GetString("auth_login_input_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string auth_login_input_rememberme {
            get {
                return ResourceManager.GetString("auth_login_input_rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string auth_login_input_username {
            get {
                return ResourceManager.GetString("auth_login_input_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string auth_login_login_button_title {
            get {
                return ResourceManager.GetString("auth_login_login_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now.
        /// </summary>
        public static string auth_login_register_button_title {
            get {
                return ResourceManager.GetString("auth_login_register_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string auth_login_resetpassword_title {
            get {
                return ResourceManager.GetString("auth_login_resetpassword_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string auth_login_title {
            get {
                return ResourceManager.GetString("auth_login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string auth_register_input_confirmpassword {
            get {
                return ResourceManager.GetString("auth_register_input_confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string auth_register_input_email {
            get {
                return ResourceManager.GetString("auth_register_input_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string auth_register_input_password {
            get {
                return ResourceManager.GetString("auth_register_input_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string auth_register_input_username {
            get {
                return ResourceManager.GetString("auth_register_input_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login here.
        /// </summary>
        public static string auth_register_login_title {
            get {
                return ResourceManager.GetString("auth_register_login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string auth_register_register_button_title {
            get {
                return ResourceManager.GetString("auth_register_register_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register here.
        /// </summary>
        public static string auth_register_title {
            get {
                return ResourceManager.GetString("auth_register_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string auth_resetpassword_input_email {
            get {
                return ResourceManager.GetString("auth_resetpassword_input_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string auth_resetpassword_input_username {
            get {
                return ResourceManager.GetString("auth_resetpassword_input_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login here.
        /// </summary>
        public static string auth_resetpassword_login_button_title {
            get {
                return ResourceManager.GetString("auth_resetpassword_login_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string auth_resetpassword_resetpassword_button_title {
            get {
                return ResourceManager.GetString("auth_resetpassword_resetpassword_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string auth_resetpassword_title {
            get {
                return ResourceManager.GetString("auth_resetpassword_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string frontend_navigation_homepage {
            get {
                return ResourceManager.GetString("frontend_navigation_homepage", resourceCulture);
            }
        }
    }
}
