//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrandBook.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrandBook.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Brand.
        /// </summary>
        public static string app_brandoverview_openbrand_button_title {
            get {
                return ResourceManager.GetString("app_brandoverview_openbrand_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string auth_back_button_title {
            get {
                return ResourceManager.GetString("auth_back_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string auth_login_external_facebook_title {
            get {
                return ResourceManager.GetString("auth_login_external_facebook_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.
        /// </summary>
        public static string auth_login_external_microsoft_title {
            get {
                return ResourceManager.GetString("auth_login_external_microsoft_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (available soon).
        /// </summary>
        public static string auth_login_external_soonavailable {
            get {
                return ResourceManager.GetString("auth_login_external_soonavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Login.
        /// </summary>
        public static string auth_login_external_title {
            get {
                return ResourceManager.GetString("auth_login_external_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string auth_login_input_password {
            get {
                return ResourceManager.GetString("auth_login_input_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string auth_login_input_rememberme {
            get {
                return ResourceManager.GetString("auth_login_input_rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string auth_login_input_username {
            get {
                return ResourceManager.GetString("auth_login_input_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string auth_login_login_button_title {
            get {
                return ResourceManager.GetString("auth_login_login_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now.
        /// </summary>
        public static string auth_login_register_button_title {
            get {
                return ResourceManager.GetString("auth_login_register_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string auth_login_resetpassword_title {
            get {
                return ResourceManager.GetString("auth_login_resetpassword_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string auth_login_title {
            get {
                return ResourceManager.GetString("auth_login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and accept the Privacy Policy.
        /// </summary>
        public static string auth_register_checkbox_privacypolicy_title {
            get {
                return ResourceManager.GetString("auth_register_checkbox_privacypolicy_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to accept the Privacy Policy.
        /// </summary>
        public static string auth_register_checkbox_privacypolicy_validation {
            get {
                return ResourceManager.GetString("auth_register_checkbox_privacypolicy_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string auth_register_external_facebook_title {
            get {
                return ResourceManager.GetString("auth_register_external_facebook_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.
        /// </summary>
        public static string auth_register_external_microsoft_title {
            get {
                return ResourceManager.GetString("auth_register_external_microsoft_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (available soon).
        /// </summary>
        public static string auth_register_external_soonavailable {
            get {
                return ResourceManager.GetString("auth_register_external_soonavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Login.
        /// </summary>
        public static string auth_register_external_title {
            get {
                return ResourceManager.GetString("auth_register_external_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string auth_register_input_confirmpassword {
            get {
                return ResourceManager.GetString("auth_register_input_confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string auth_register_input_email {
            get {
                return ResourceManager.GetString("auth_register_input_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string auth_register_input_password {
            get {
                return ResourceManager.GetString("auth_register_input_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string auth_register_input_username {
            get {
                return ResourceManager.GetString("auth_register_input_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login here.
        /// </summary>
        public static string auth_register_login_title {
            get {
                return ResourceManager.GetString("auth_register_login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string auth_register_register_button_title {
            get {
                return ResourceManager.GetString("auth_register_register_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register here.
        /// </summary>
        public static string auth_register_title {
            get {
                return ResourceManager.GetString("auth_register_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string auth_resetpassword_input_email {
            get {
                return ResourceManager.GetString("auth_resetpassword_input_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string auth_resetpassword_input_username {
            get {
                return ResourceManager.GetString("auth_resetpassword_input_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login here.
        /// </summary>
        public static string auth_resetpassword_login_button_title {
            get {
                return ResourceManager.GetString("auth_resetpassword_login_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string auth_resetpassword_resetpassword_button_title {
            get {
                return ResourceManager.GetString("auth_resetpassword_resetpassword_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string auth_resetpassword_title {
            get {
                return ResourceManager.GetString("auth_resetpassword_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie Terms.
        /// </summary>
        public static string frontend_footer_legal_cookieterms {
            get {
                return ResourceManager.GetString("frontend_footer_legal_cookieterms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprint.
        /// </summary>
        public static string frontend_footer_legal_imprint {
            get {
                return ResourceManager.GetString("frontend_footer_legal_imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string frontend_footer_legal_privacypolicy {
            get {
                return ResourceManager.GetString("frontend_footer_legal_privacypolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions.
        /// </summary>
        public static string frontend_footer_legal_terms {
            get {
                return ResourceManager.GetString("frontend_footer_legal_terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal.
        /// </summary>
        public static string frontend_footer_legal_title {
            get {
                return ResourceManager.GetString("frontend_footer_legal_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string frontend_footer_product_documentation {
            get {
                return ResourceManager.GetString("frontend_footer_product_documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string frontend_footer_product_examples {
            get {
                return ResourceManager.GetString("frontend_footer_product_examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string frontend_footer_product_pricing {
            get {
                return ResourceManager.GetString("frontend_footer_product_pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solutions.
        /// </summary>
        public static string frontend_footer_product_solutions {
            get {
                return ResourceManager.GetString("frontend_footer_product_solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string frontend_footer_product_title {
            get {
                return ResourceManager.GetString("frontend_footer_product_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string frontend_footer_support_contact {
            get {
                return ResourceManager.GetString("frontend_footer_support_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        public static string frontend_footer_support_forum {
            get {
                return ResourceManager.GetString("frontend_footer_support_forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug.
        /// </summary>
        public static string frontend_footer_support_reportabug {
            get {
                return ResourceManager.GetString("frontend_footer_support_reportabug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string frontend_footer_support_title {
            get {
                return ResourceManager.GetString("frontend_footer_support_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string frontend_legal_cookieconsent_accept_button_text {
            get {
                return ResourceManager.GetString("frontend_legal_cookieconsent_accept_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find out more here.
        /// </summary>
        public static string frontend_legal_cookieconsent_link_text {
            get {
                return ResourceManager.GetString("frontend_legal_cookieconsent_link_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use cookies to give you the best online experience. By using our website, you agree to our use of cookies in accordance with our cookie policy..
        /// </summary>
        public static string frontend_legal_cookieconsent_text {
            get {
                return ResourceManager.GetString("frontend_legal_cookieconsent_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open App.
        /// </summary>
        public static string frontend_navigation_authorized_gotoapp {
            get {
                return ResourceManager.GetString("frontend_navigation_authorized_gotoapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string frontend_navigation_contact {
            get {
                return ResourceManager.GetString("frontend_navigation_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Features.
        /// </summary>
        public static string frontend_navigation_function_plannedfeatures {
            get {
                return ResourceManager.GetString("frontend_navigation_function_plannedfeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functionality.
        /// </summary>
        public static string frontend_navigation_functions {
            get {
                return ResourceManager.GetString("frontend_navigation_functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Improvement (AI).
        /// </summary>
        public static string frontend_navigation_functions_brandimprovement {
            get {
                return ResourceManager.GetString("frontend_navigation_functions_brandimprovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Management.
        /// </summary>
        public static string frontend_navigation_functions_brandmanagement {
            get {
                return ResourceManager.GetString("frontend_navigation_functions_brandmanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string frontend_navigation_homepage {
            get {
                return ResourceManager.GetString("frontend_navigation_homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string frontend_navigation_login_button {
            get {
                return ResourceManager.GetString("frontend_navigation_login_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string frontend_navigation_pricing {
            get {
                return ResourceManager.GetString("frontend_navigation_pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string frontend_navigation_register_button {
            get {
                return ResourceManager.GetString("frontend_navigation_register_button", resourceCulture);
            }
        }
    }
}
