//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrandBook.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrandBook.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Brand.
        /// </summary>
        public static string app_brandoverview_openbrand_button_title {
            get {
                return ResourceManager.GetString("app_brandoverview_openbrand_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your preferred language for the userinterface.
        /// </summary>
        public static string app_culturesetting_description {
            get {
                return ResourceManager.GetString("app_culturesetting_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string app_culturesetting_save_button_title {
            get {
                return ResourceManager.GetString("app_culturesetting_save_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Selection.
        /// </summary>
        public static string app_culturesetting_title {
            get {
                return ResourceManager.GetString("app_culturesetting_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string app_culturesetting_value_active {
            get {
                return ResourceManager.GetString("app_culturesetting_value_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string app_mainnavigation_dashboard {
            get {
                return ResourceManager.GetString("app_mainnavigation_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string app_mainnavigation_usermanagement_company {
            get {
                return ResourceManager.GetString("app_mainnavigation_usermanagement_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string app_mainnavigation_usermanagement_roles {
            get {
                return ResourceManager.GetString("app_mainnavigation_usermanagement_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string app_mainnavigation_usermanagement_user {
            get {
                return ResourceManager.GetString("app_mainnavigation_usermanagement_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usermanagement.
        /// </summary>
        public static string app_mainnavigation_usermanagement_usermanagement {
            get {
                return ResourceManager.GetString("app_mainnavigation_usermanagement_usermanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Brands.
        /// </summary>
        public static string app_mainnavigation_yourbrands {
            get {
                return ResourceManager.GetString("app_mainnavigation_yourbrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string app_settings_back_button_title {
            get {
                return ResourceManager.GetString("app_settings_back_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings regarding the Brands.
        /// </summary>
        public static string app_settings_brand_description {
            get {
                return ResourceManager.GetString("app_settings_brand_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Settings.
        /// </summary>
        public static string app_settings_brand_title {
            get {
                return ResourceManager.GetString("app_settings_brand_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage of Media.
        /// </summary>
        public static string app_settings_media_description {
            get {
                return ResourceManager.GetString("app_settings_media_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Settings.
        /// </summary>
        public static string app_settings_media_title {
            get {
                return ResourceManager.GetString("app_settings_media_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this page you find all relevant Settings. Please contact the administrator if you have questions..
        /// </summary>
        public static string app_settings_overview_description {
            get {
                return ResourceManager.GetString("app_settings_overview_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string app_settings_overview_open_button_title {
            get {
                return ResourceManager.GetString("app_settings_overview_open_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string app_settings_overview_title {
            get {
                return ResourceManager.GetString("app_settings_overview_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The App Title will is shown in the Browser Tab..
        /// </summary>
        public static string app_settings_system_apptitle_description {
            get {
                return ResourceManager.GetString("app_settings_system_apptitle_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Title.
        /// </summary>
        public static string app_settings_system_apptitle_title {
            get {
                return ResourceManager.GetString("app_settings_system_apptitle_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important System Settings.
        /// </summary>
        public static string app_settings_system_description {
            get {
                return ResourceManager.GetString("app_settings_system_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the Email to specify from which E-Mail Address System-E-Mails should be sent..
        /// </summary>
        public static string app_settings_system_emailsender_description {
            get {
                return ResourceManager.GetString("app_settings_system_emailsender_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Sender.
        /// </summary>
        public static string app_settings_system_emailsender_title {
            get {
                return ResourceManager.GetString("app_settings_system_emailsender_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the Base Url of the BrandBook Installation. This setting is important for Systemmails and larger redirects..
        /// </summary>
        public static string app_settings_system_systembaseurl_description {
            get {
                return ResourceManager.GetString("app_settings_system_systembaseurl_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Base Url.
        /// </summary>
        public static string app_settings_system_systembaseurl_title {
            get {
                return ResourceManager.GetString("app_settings_system_systembaseurl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings.
        /// </summary>
        public static string app_settings_system_title {
            get {
                return ResourceManager.GetString("app_settings_system_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string app_settings_update_button_title {
            get {
                return ResourceManager.GetString("app_settings_update_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Settings.
        /// </summary>
        public static string app_settings_user_description {
            get {
                return ResourceManager.GetString("app_settings_user_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Settings.
        /// </summary>
        public static string app_settings_user_title {
            get {
                return ResourceManager.GetString("app_settings_user_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string app_usermenu_languageselection {
            get {
                return ResourceManager.GetString("app_usermenu_languageselection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave app.
        /// </summary>
        public static string app_usermenu_leaveapp {
            get {
                return ResourceManager.GetString("app_usermenu_leaveapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string app_usermenu_logout {
            get {
                return ResourceManager.GetString("app_usermenu_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string app_usermenu_profile {
            get {
                return ResourceManager.GetString("app_usermenu_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string app_usermenu_settings {
            get {
                return ResourceManager.GetString("app_usermenu_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string auth_back_button_title {
            get {
                return ResourceManager.GetString("auth_back_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string auth_login_external_facebook_title {
            get {
                return ResourceManager.GetString("auth_login_external_facebook_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.
        /// </summary>
        public static string auth_login_external_microsoft_title {
            get {
                return ResourceManager.GetString("auth_login_external_microsoft_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (available soon).
        /// </summary>
        public static string auth_login_external_soonavailable {
            get {
                return ResourceManager.GetString("auth_login_external_soonavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Login.
        /// </summary>
        public static string auth_login_external_title {
            get {
                return ResourceManager.GetString("auth_login_external_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string auth_login_input_password {
            get {
                return ResourceManager.GetString("auth_login_input_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string auth_login_input_rememberme {
            get {
                return ResourceManager.GetString("auth_login_input_rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string auth_login_input_username {
            get {
                return ResourceManager.GetString("auth_login_input_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string auth_login_login_button_title {
            get {
                return ResourceManager.GetString("auth_login_login_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now.
        /// </summary>
        public static string auth_login_register_button_title {
            get {
                return ResourceManager.GetString("auth_login_register_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string auth_login_resetpassword_title {
            get {
                return ResourceManager.GetString("auth_login_resetpassword_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string auth_login_title {
            get {
                return ResourceManager.GetString("auth_login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and accept the Privacy Policy.
        /// </summary>
        public static string auth_register_checkbox_privacypolicy_title {
            get {
                return ResourceManager.GetString("auth_register_checkbox_privacypolicy_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to accept the Privacy Policy.
        /// </summary>
        public static string auth_register_checkbox_privacypolicy_validation {
            get {
                return ResourceManager.GetString("auth_register_checkbox_privacypolicy_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string auth_register_external_facebook_title {
            get {
                return ResourceManager.GetString("auth_register_external_facebook_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.
        /// </summary>
        public static string auth_register_external_microsoft_title {
            get {
                return ResourceManager.GetString("auth_register_external_microsoft_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (available soon).
        /// </summary>
        public static string auth_register_external_soonavailable {
            get {
                return ResourceManager.GetString("auth_register_external_soonavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Login.
        /// </summary>
        public static string auth_register_external_title {
            get {
                return ResourceManager.GetString("auth_register_external_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string auth_register_input_confirmpassword {
            get {
                return ResourceManager.GetString("auth_register_input_confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string auth_register_input_email {
            get {
                return ResourceManager.GetString("auth_register_input_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string auth_register_input_password {
            get {
                return ResourceManager.GetString("auth_register_input_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string auth_register_input_username {
            get {
                return ResourceManager.GetString("auth_register_input_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login here.
        /// </summary>
        public static string auth_register_login_title {
            get {
                return ResourceManager.GetString("auth_register_login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string auth_register_register_button_title {
            get {
                return ResourceManager.GetString("auth_register_register_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register here.
        /// </summary>
        public static string auth_register_title {
            get {
                return ResourceManager.GetString("auth_register_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string auth_resetpassword_input_email {
            get {
                return ResourceManager.GetString("auth_resetpassword_input_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string auth_resetpassword_input_username {
            get {
                return ResourceManager.GetString("auth_resetpassword_input_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login here.
        /// </summary>
        public static string auth_resetpassword_login_button_title {
            get {
                return ResourceManager.GetString("auth_resetpassword_login_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string auth_resetpassword_resetpassword_button_title {
            get {
                return ResourceManager.GetString("auth_resetpassword_resetpassword_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string auth_resetpassword_title {
            get {
                return ResourceManager.GetString("auth_resetpassword_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved..
        /// </summary>
        public static string frontend_footer_allrightsreserved {
            get {
                return ResourceManager.GetString("frontend_footer_allrightsreserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philipp C. Moser.
        /// </summary>
        public static string frontend_footer_copyright {
            get {
                return ResourceManager.GetString("frontend_footer_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie Terms.
        /// </summary>
        public static string frontend_footer_legal_cookieterms {
            get {
                return ResourceManager.GetString("frontend_footer_legal_cookieterms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprint.
        /// </summary>
        public static string frontend_footer_legal_imprint {
            get {
                return ResourceManager.GetString("frontend_footer_legal_imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string frontend_footer_legal_privacypolicy {
            get {
                return ResourceManager.GetString("frontend_footer_legal_privacypolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions.
        /// </summary>
        public static string frontend_footer_legal_terms {
            get {
                return ResourceManager.GetString("frontend_footer_legal_terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal.
        /// </summary>
        public static string frontend_footer_legal_title {
            get {
                return ResourceManager.GetString("frontend_footer_legal_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string frontend_footer_product_documentation {
            get {
                return ResourceManager.GetString("frontend_footer_product_documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string frontend_footer_product_examples {
            get {
                return ResourceManager.GetString("frontend_footer_product_examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string frontend_footer_product_pricing {
            get {
                return ResourceManager.GetString("frontend_footer_product_pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        public static string frontend_footer_product_solutions {
            get {
                return ResourceManager.GetString("frontend_footer_product_solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string frontend_footer_product_title {
            get {
                return ResourceManager.GetString("frontend_footer_product_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string frontend_footer_support_contact {
            get {
                return ResourceManager.GetString("frontend_footer_support_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        public static string frontend_footer_support_forum {
            get {
                return ResourceManager.GetString("frontend_footer_support_forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug.
        /// </summary>
        public static string frontend_footer_support_reportabug {
            get {
                return ResourceManager.GetString("frontend_footer_support_reportabug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string frontend_footer_support_title {
            get {
                return ResourceManager.GetString("frontend_footer_support_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and document your company branding step by step. Our intelligent editor helps you with your existing data..
        /// </summary>
        public static string frontend_home_index_features_feature_01_description {
            get {
                return ResourceManager.GetString("frontend_home_index_features_feature_01_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation.
        /// </summary>
        public static string frontend_home_index_features_feature_01_title {
            get {
                return ResourceManager.GetString("frontend_home_index_features_feature_01_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Through many tips and tricks you will learn how to use your brand to advantage and provide it to others..
        /// </summary>
        public static string frontend_home_index_features_feature_02_description {
            get {
                return ResourceManager.GetString("frontend_home_index_features_feature_02_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string frontend_home_index_features_feature_02_title {
            get {
                return ResourceManager.GetString("frontend_home_index_features_feature_02_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous and automated tests constantly check your brand for optimization possibilities and implement them as you wish..
        /// </summary>
        public static string frontend_home_index_features_feature_03_description {
            get {
                return ResourceManager.GetString("frontend_home_index_features_feature_03_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improvement.
        /// </summary>
        public static string frontend_home_index_features_feature_03_title {
            get {
                return ResourceManager.GetString("frontend_home_index_features_feature_03_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why BrandCi leads your Brand.
        /// </summary>
        public static string frontend_home_index_features_title_l1 {
            get {
                return ResourceManager.GetString("frontend_home_index_features_title_l1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to success.
        /// </summary>
        public static string frontend_home_index_features_title_l2 {
            get {
                return ResourceManager.GetString("frontend_home_index_features_title_l2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to know more?.
        /// </summary>
        public static string frontend_home_index_intro_button_description {
            get {
                return ResourceManager.GetString("frontend_home_index_intro_button_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here..
        /// </summary>
        public static string frontend_home_index_intro_button_title {
            get {
                return ResourceManager.GetString("frontend_home_index_intro_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us introduce you BrandCi.
        /// </summary>
        public static string frontend_home_index_intro_heading {
            get {
                return ResourceManager.GetString("frontend_home_index_intro_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is BrandCi?.
        /// </summary>
        public static string frontend_home_index_intro_subheading {
            get {
                return ResourceManager.GetString("frontend_home_index_intro_subheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string frontend_home_index_intro_subtext {
            get {
                return ResourceManager.GetString("frontend_home_index_intro_subtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string frontend_home_index_intro_text {
            get {
                return ResourceManager.GetString("frontend_home_index_intro_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more..
        /// </summary>
        public static string frontend_home_index_services_button_title {
            get {
                return ResourceManager.GetString("frontend_home_index_services_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan and improve your brand online without any additional software and work together with your colleagues on the success of your brand..
        /// </summary>
        public static string frontend_home_index_services_service_01_description {
            get {
                return ResourceManager.GetString("frontend_home_index_services_service_01_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to your brand. From everywhere..
        /// </summary>
        public static string frontend_home_index_services_service_01_title {
            get {
                return ResourceManager.GetString("frontend_home_index_services_service_01_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A redesign of your brand contributes to the brand&apos;s success through intelligent advance planning..
        /// </summary>
        public static string frontend_home_index_services_service_02_description {
            get {
                return ResourceManager.GetString("frontend_home_index_services_service_02_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand your brand. Well planned..
        /// </summary>
        public static string frontend_home_index_services_service_02_title {
            get {
                return ResourceManager.GetString("frontend_home_index_services_service_02_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Through the use of Artificial Intelligence, we provide you and your brand a steady improvement..
        /// </summary>
        public static string frontend_home_index_services_service_03_description {
            get {
                return ResourceManager.GetString("frontend_home_index_services_service_03_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous improvement. Thanks to AI..
        /// </summary>
        public static string frontend_home_index_services_service_03_title {
            get {
                return ResourceManager.GetString("frontend_home_index_services_service_03_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your agencies access to your brand. Set up a private space with a lot of information for your agencies. You can also publish your brands for everyone..
        /// </summary>
        public static string frontend_home_index_services_service_04_description {
            get {
                return ResourceManager.GetString("frontend_home_index_services_service_04_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share your brand. With everybody you want..
        /// </summary>
        public static string frontend_home_index_services_service_04_title {
            get {
                return ResourceManager.GetString("frontend_home_index_services_service_04_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover BrandCi.
        /// </summary>
        public static string frontend_home_index_topsection_discover_button_title {
            get {
                return ResourceManager.GetString("frontend_home_index_topsection_discover_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage and improve your brand image..
        /// </summary>
        public static string frontend_home_index_topsection_subtitle {
            get {
                return ResourceManager.GetString("frontend_home_index_topsection_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Brand Ci for free.
        /// </summary>
        public static string frontend_home_index_topsection_test_button_title {
            get {
                return ResourceManager.GetString("frontend_home_index_topsection_test_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your digital brand..
        /// </summary>
        public static string frontend_home_index_topsection_title_l1 {
            get {
                return ResourceManager.GetString("frontend_home_index_topsection_title_l1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your success..
        /// </summary>
        public static string frontend_home_index_topsection_title_l2 {
            get {
                return ResourceManager.GetString("frontend_home_index_topsection_title_l2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string frontend_legal_cookieconsent_accept_button_text {
            get {
                return ResourceManager.GetString("frontend_legal_cookieconsent_accept_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find out more here.
        /// </summary>
        public static string frontend_legal_cookieconsent_link_text {
            get {
                return ResourceManager.GetString("frontend_legal_cookieconsent_link_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use cookies to give you the best online experience. By using our website, you agree to our use of cookies in accordance with our cookie policy..
        /// </summary>
        public static string frontend_legal_cookieconsent_text {
            get {
                return ResourceManager.GetString("frontend_legal_cookieconsent_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open App.
        /// </summary>
        public static string frontend_navigation_authorized_gotoapp {
            get {
                return ResourceManager.GetString("frontend_navigation_authorized_gotoapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string frontend_navigation_contact {
            get {
                return ResourceManager.GetString("frontend_navigation_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string frontend_navigation_homepage {
            get {
                return ResourceManager.GetString("frontend_navigation_homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string frontend_navigation_login_button {
            get {
                return ResourceManager.GetString("frontend_navigation_login_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string frontend_navigation_pricing {
            get {
                return ResourceManager.GetString("frontend_navigation_pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string frontend_navigation_product {
            get {
                return ResourceManager.GetString("frontend_navigation_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Creation.
        /// </summary>
        public static string frontend_navigation_product_brandcreation {
            get {
                return ResourceManager.GetString("frontend_navigation_product_brandcreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Optimization.
        /// </summary>
        public static string frontend_navigation_product_brandimprovement {
            get {
                return ResourceManager.GetString("frontend_navigation_product_brandimprovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Management.
        /// </summary>
        public static string frontend_navigation_product_brandmanagement {
            get {
                return ResourceManager.GetString("frontend_navigation_product_brandmanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string frontend_navigation_product_overview {
            get {
                return ResourceManager.GetString("frontend_navigation_product_overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Features.
        /// </summary>
        public static string frontend_navigation_product_plannedfeatures {
            get {
                return ResourceManager.GetString("frontend_navigation_product_plannedfeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string frontend_navigation_register_button {
            get {
                return ResourceManager.GetString("frontend_navigation_register_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de-DE.
        /// </summary>
        public static string system_culture_de_de {
            get {
                return ResourceManager.GetString("system_culture_de_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German (Germany).
        /// </summary>
        public static string system_culture_de_de_full {
            get {
                return ResourceManager.GetString("system_culture_de_de_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string system_culture_en_us {
            get {
                return ResourceManager.GetString("system_culture_en_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (United States).
        /// </summary>
        public static string system_culture_en_us_full {
            get {
                return ResourceManager.GetString("system_culture_en_us_full", resourceCulture);
            }
        }
    }
}
